<a href="https://colab.research.google.com/github/veeransr/ML-and-Deep-learning-practice-with-python/blob/master/NN_forward_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np # import Numpy library to generate 

weights = np.around(np.random.uniform(size=6), decimals=2) # initialize the weights
biases = np.around(np.random.uniform(size=3), decimals=2) # initialize the biases


In [0]:
print(weights)
print(biases)

[0.49 0.31 0.74 0.95 0.09 0.8 ]
[0.26 0.06 0.66]


In [0]:
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

print('x1 is {} and x2 is {}'.format(x_1, x_2))

x1 is 0.5 and x2 is 0.85


In [0]:
z_11 = x_1 * weights[0] + x_2 * weights[1] + biases[0]

print('The weighted sum of the inputs at the first node in the hidden layer is {}'.format(z_11))

The weighted sum of the inputs at the first node in the hidden layer is 0.7685


In [0]:
z_12 = x_1 * weights[2] + x_2 * weights[3] + biases[1]

print('The weighted sum of the inputs at the first node in the hidden layer is {}'.format(z_12))

The weighted sum of the inputs at the first node in the hidden layer is 1.2375


Next, assuming a sigmoid activation function, let's compute the activation of the first node,  𝑎1,1 , in the hidden layer.

In [0]:
a_11 = 1.0 / (1.0 + np.exp(-z_11))

print('The activation of the first node in the hidden layer is {}'.format(np.around(a_11, decimals=4)))

The activation of the first node in the hidden layer is 0.7751


In [0]:
a_12 = 1.0/ (1.0+np.exp(-z_12))
print('The sigoid function of activation at hidden layer node 2 is : {}'.format(np.around(a_12, decimals =4)))

The sigoid function of activation at hidden layer node 2 is : 0.7751


Now these activations will serve as the inputs to the output layer. So, let's compute the weighted sum of these inputs to the node in the output layer. Assign the value to z_2.

In [0]:
z_2 = a_11*weights[4]+a_12*weights[5]+biases[2]
print('the sum of weighted inputs for the outputlayer : {}'.format(np.around(z_2, decimals =4)))

the sum of weighted inputs for the outputlayer : 1.3499


In [0]:
a_2 = 1/(1+ np.exp(-z_2))
print('The sigmoid activation function at output layer resulted : {}'. format(np.around(a_2, decimals = 4)))

The sigmoid activation function at output layer resulted : 0.7941


Obviously, neural networks for real problems are composed of many hidden layers and many more nodes in each layer. So, we can't continue making predictions using this very inefficient approach of computing the weighted sum at each node and the activation of each node manually.

In order to code an automatic way of making predictions, let's generalize our network. A general network would take  𝑛  inputs, would have many hidden layers, each hidden layer having  𝑚  nodes, and would have an output layer. Although the network is showing one hidden layer, but we will code the network to have many hidden layers. Similarly, although the network shows an output layer with one node, we will code the network to have more than one node in the output layer.
![alt text](https://)

Neural Network General


Initialize a Network
Let's start by formally defining the structure of the network.

Initialize a Network
Let's start by formally defining the structure of the network.

In [0]:
n = 2 # number of inputs
num_hidden_layers = 2 # number of hidden layers
m = [2, 2] # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer

Now that we defined the structure of the network, let's go ahead and inititailize the weights and the biases in the network to random numbers. In order to be able to initialize the weights and the biases to random numbers, we will need to import the Numpy library.

In [0]:
import numpy as np # import the Numpy library

num_nodes_previous = n # number of nodes in the previous layer

network = {} # initialize network an an empty dictionary

# loop through each layer and randomly initialize the weights and biases associated with each node
# notice how we are adding 1 to the number of hidden layers in order to include the output layer
for layer in range(num_hidden_layers + 1): 
   
    
    # determine name of layer
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
        
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network

{'layer_1': {'node_1': {'weights': array([0.97, 0.5 ]), 'bias': array([0.43])}, 'node_2': {'weights': array([0.42, 0.69]), 'bias': array([0.93])}}, 'layer_2': {'node_1': {'weights': array([0.02, 0.97]), 'bias': array([0.62])}, 'node_2': {'weights': array([0.13, 0.91]), 'bias': array([0.1])}}, 'output': {'node_1': {'weights': array([0.08, 0.41]), 'bias': array([0.92])}}}


Awesome! So now with the above code, we are able to initialize the weights and the biases pertaining to any network of any number of hidden layers and number of nodes in each layer. But let's put this code in a function so that we are able to repetitively execute all this code whenever we want to construct a neural network.

In [0]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

The above code is not working so midified

In [0]:
def initialize_network2(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer
    m = np.full((num_nodes_hidden),num_nodes_hidden)
    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = m[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [0]:
y = initialize_network2(100, 10, 10, 1)
y

{'layer_1': {'node_1': {'bias': array([0.76]),
   'weights': array([0.75, 0.61, 0.54, 0.82, 0.27, 0.32, 0.12, 0.3 , 1.  , 0.93, 0.93,
          0.53, 0.4 , 0.14, 0.99, 0.8 , 0.06, 0.24, 0.49, 0.76, 0.71, 0.9 ,
          0.28, 0.96, 0.6 , 0.22, 0.86, 0.89, 0.23, 0.44, 0.46, 0.35, 0.72,
          0.43, 0.11, 0.82, 0.66, 0.82, 0.63, 0.61, 0.27, 0.08, 0.41, 0.96,
          0.52, 0.59, 0.75, 0.95, 0.24, 0.28, 0.92, 0.22, 0.42, 0.51, 0.57,
          0.92, 0.95, 0.27, 0.31, 0.72, 0.57, 0.25, 0.07, 0.96, 0.39, 0.46,
          0.05, 0.08, 0.82, 0.94, 0.78, 0.64, 0.69, 0.46, 0.37, 0.16, 0.9 ,
          0.14, 0.88, 0.72, 0.06, 0.36, 0.16, 0.13, 0.44, 0.66, 0.56, 0.43,
          0.6 , 0.04, 0.86, 0.27, 0.06, 0.54, 0.72, 0.37, 0.75, 0.48, 0.29,
          0.91])},
  'node_10': {'bias': array([0.11]),
   'weights': array([0.87, 0.85, 0.99, 0.44, 0.65, 0.63, 0.74, 0.54, 0.25, 0.76, 0.82,
          0.81, 0.87, 0.3 , 0.91, 0.26, 0.24, 0.  , 0.8 , 0.58, 0.71, 0.07,
          0.89, 0.68, 0.82, 0.19, 0.12,

In [0]:
x= initialize_network(100, 10, 10, 1)
x

{'layer_1': {'node_1': {'bias': array([0.15]),
   'weights': array([0.44, 0.46, 0.74, 0.21, 0.21, 0.69, 0.71, 0.68, 0.27, 0.81, 0.66,
          0.44, 0.44, 0.73, 0.19, 0.7 , 0.08, 0.48, 0.83, 0.41, 0.44, 0.49,
          0.82, 0.15, 0.38, 0.94, 0.02, 0.24, 0.34, 0.22, 0.15, 0.81, 0.57,
          0.89, 0.63, 0.7 , 0.31, 0.29, 0.24, 0.78, 0.96, 0.14, 0.7 , 0.68,
          0.6 , 0.72, 0.37, 0.66, 0.59, 0.51, 0.95, 0.88, 0.82, 0.87, 0.67,
          0.07, 0.43, 0.86, 0.67, 0.37, 0.14, 0.55, 0.15, 0.33, 0.84, 0.3 ,
          0.54, 0.85, 0.59, 0.47, 0.33, 0.55, 0.32, 0.38, 0.27, 0.67, 0.51,
          0.52, 0.91, 0.07, 0.87, 0.66, 0.57, 0.91, 0.51, 0.03, 0.04, 0.36,
          0.01, 0.41, 0.84, 0.6 , 0.63, 0.77, 0.09, 0.62, 0.51, 0.88, 0.78,
          0.28])},
  'node_10': {'bias': array([0.81]),
   'weights': array([0.55, 0.73, 0.92, 0.15, 0.  , 0.73, 0.02, 0.89, 0.23, 0.3 , 0.47,
          0.58, 0.13, 0.66, 0.99, 0.83, 0.21, 0.18, 0.52, 0.41, 0.12, 0.06,
          0.26, 0.28, 0.23, 1.  , 0.66,

[10 10 10 10 10 10 10 10 10 10]


In [0]:
x= initialize_network(5, 3, 3, 1)
x

{'layer_1': {'node_1': {'bias': array([0.85]),
   'weights': array([0.32, 0.5 , 0.36, 0.21, 0.52])},
  'node_2': {'bias': array([0.68]),
   'weights': array([0.65, 0.88, 0.32, 0.33, 1.  ])},
  'node_3': {'bias': array([0.1]),
   'weights': array([0.64, 0.08, 0.39, 0.13, 0.63])}},
 'layer_2': {'node_1': {'bias': array([0.14]),
   'weights': array([0.01, 0.18, 0.85])},
  'node_2': {'bias': array([0.86]), 'weights': array([0.34, 0.5 , 0.75])},
  'node_3': {'bias': array([1.]), 'weights': array([0.43, 0.7 , 0.96])}},
 'layer_3': {'node_1': {'bias': array([0.75]),
   'weights': array([0.6 , 0.6 , 0.36])},
  'node_2': {'bias': array([0.55]), 'weights': array([0.56, 0.31, 0.95])},
  'node_3': {'bias': array([0.77]), 'weights': array([0.18, 0.44, 0.69])}},
 'output': {'node_1': {'bias': array([0.93]),
   'weights': array([0.95, 0.28, 0.65])}}}

1. takes 5 inputs
2. has three hidden layers
3. has 3 nodes in the first layer, 2 nodes in the second layer, and 3 nodes in the third layer
4. has 1 node in the output layer

Call the network **small_network**.

In [0]:
def initialize_network1(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer
    #m = np.full((num_nodes_hidden),num_nodes_hidden)
    m= [3,2,3]
    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = m[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [0]:
small_network = initialize_network1(5,3,3,1)
small_network 

{'layer_1': {'node_1': {'bias': array([0.13]),
   'weights': array([0.71, 0.26, 0.66, 0.15, 0.55])},
  'node_2': {'bias': array([0.9]),
   'weights': array([0.86, 0.97, 0.75, 0.69, 0.89])},
  'node_3': {'bias': array([0.83]),
   'weights': array([0.6 , 0.22, 0.99, 0.82, 0.28])}},
 'layer_2': {'node_1': {'bias': array([0.65]),
   'weights': array([0.97, 0.21, 0.8 ])},
  'node_2': {'bias': array([0.94]), 'weights': array([0.89, 0.29, 0.56])}},
 'layer_3': {'node_1': {'bias': array([0.16]), 'weights': array([0.29, 0.19])},
  'node_2': {'bias': array([0.05]), 'weights': array([0.68, 0.2 ])},
  'node_3': {'bias': array([0.5]), 'weights': array([0.42, 0.05])}},
 'output': {'node_1': {'bias': array([0.78]),
   'weights': array([0.74, 0.95, 0.83])}}}

In [0]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer
    m = np.full((num_nodes_hidden),num_nodes_hidden)
    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = m[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [0]:
small_network = initialize_network(5, 3, [3, 2, 3], 1)
small_network

{'layer_1': {'node_1': {'bias': array([0.28]),
   'weights': array([0.92, 0.9 , 0.03, 0.96, 0.14])},
  'node_2': {'bias': array([0.55]),
   'weights': array([0.61, 0.94, 0.85, 0.  , 0.52])},
  'node_3': {'bias': array([0.14]),
   'weights': array([0.49, 0.77, 0.16, 0.76, 0.02])}},
 'layer_2': {'node_1': {'bias': array([0.47]),
   'weights': array([0.12, 0.31, 0.67])},
  'node_2': {'bias': array([0.7]), 'weights': array([0.82, 0.29, 0.73])}},
 'layer_3': {'node_1': {'bias': array([0.98]), 'weights': array([0.33, 0.33])},
  'node_2': {'bias': array([0.77]), 'weights': array([0.62, 0.95])},
  'node_3': {'bias': array([0.45]), 'weights': array([0.83, 0.41])}},
 'output': {'node_1': {'bias': array([0.96]),
   'weights': array([0.4 , 1.  , 0.18])}}}

Compute Weighted Sum at Each Node
The weighted sum at each node is computed as the dot product of the inputs and the weights plus the bias. So let's create a function called compute_weighted_sum that does just that.

In [0]:
small_network.keys()

dict_keys(['layer_1', 'layer_2', 'layer_3', 'output'])

In [0]:
small_network['layer_1']['node_1']['weights']

array([0.92, 0.9 , 0.03, 0.96, 0.14])

In [0]:
def compute_weighted_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

Let's generate 5 inputs that we can feed to small_network.

In [0]:
from random import seed
import numpy as np

np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


Use the compute_weighted_sum function to compute the weighted sum at the first node in the first hidden layer.

In [0]:
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']

weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
print('The weighted sum at the first node in the hidden layer is {}'.format(np.around(weighted_sum[0], decimals=4)))

The weighted sum at the first node in the hidden layer is 1.602


In [0]:
compute_weighted_sum(inputs,small_network['layer_1']['node_1']['weights'], small_network['layer_1']['node_1']['bias'] )

array([1.602])

Compute Node Activation
Recall that the output of each node is simply a non-linear tranformation of the weighted sum. We use activation functions for this mapping. Let's use the sigmoid function as the activation function here. So let's define a function that takes a weighted sum as input and returns the non-linear transformation of the input using the sigmoid function.

In [0]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

The above is a recursive function
below created a normal function

In [0]:
node_output  = node_activation(compute_weighted_sum(inputs, node_weights, node_bias))
print('The output of the first node in the hidden layer is {}'.format(np.around(node_output[0], decimals=4)))

The output of the first node in the hidden layer is 0.8323


In [0]:
out_put = node_activation(compute_weighted_sum(inputs,small_network['layer_1']['node_1']['weights'], small_network['layer_1']['node_1']['bias'] ))
out_put

array([0.83229773])

Forward Propagation¶
The final piece of building a neural network that can perform predictions is to put everything together. So let's create a function that applies the compute_weighted_sum and node_activation functions to each node in the network and propagates the data all the way to the output layer and outputs a prediction for each node in the output layer.

The way we are going to accomplish this is through the following procedure:

Start with the input layer as the input to the first hidden layer.
Compute the weighted sum at the nodes of the current layer.
Compute the output of the nodes of the current layer.
Set the output of the current layer to be the input to the next layer.
Move to the next layer in the network.
Repeat steps 2 - 4 until we compute the output of the output layer.

In [0]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [0]:
forward_propagate (small_network, inputs)

The outputs of the nodes in hidden layer number 1 is [0.8323, 0.8268, 0.7735]
The outputs of the nodes in hidden layer number 2 is [0.7932, 0.8991]
The outputs of the nodes in hidden layer number 3 is [0.8232, 0.8924, 0.8141]


[0.9112]

In [0]:
my_network = initialize_network(5, 3, [2, 3, 2], 3)
inputs = np.around(np.random.uniform(size=5), decimals=2)
predictions = forward_propagate(my_network, inputs)
print('The predicted values by the network for the given input are {}'.format(predictions))

The outputs of the nodes in hidden layer number 1 is [0.7794, 0.8202, 0.8474]
The outputs of the nodes in hidden layer number 2 is [0.7938, 0.8946]
The outputs of the nodes in hidden layer number 3 is [0.7941, 0.8623, 0.6507]
The predicted values by the network for the given input are [0.9298, 0.896, 0.8427]
